package lambda.core.constants

object FunctionNameConstants {
    const val ATOM = "atom"
    const val CAR = "car"
    const val CDR = "cdr"
    const val COND = "cond"
    const val CONDCHILD = "CONDCHILD"
    const val CONS = "cons"
    const val DEFUN = "DEFUN"
    const val EQ = "="
    const val GCD = "gcd"
    const val GREATER = ">"
    const val GREATER_EQ = ">="
    const val INT = "int"
    const val LCM = "lcm"
    const val LESS = "<"
    const val LESS_EQ = "<="
    const val MINUS = "-"
    const val NOT_EQ = "/="
    const val NULL = "null"
    const val PLUS = "+"
    const val QUOTE = "'"
    const val TIMES = "*"
}