package lambda.core.constants

object FunctionNameConstants {
    const val ATOM = "atom"
    const val CAR = "car"
    const val CDR = "cdr"
    const val COND = "cond"
    const val COND_CHILD = "cond_child"
    const val CONS = "cons"
    const val DEFUN = "defun"
    const val EQ = "="
    const val EVEN_P = "evenp"
    const val EXP = "exp"
    const val EXPT = "expt"
    const val GCD = "gcd"
    const val GREATER = ">"
    const val GREATER_EQ = ">="
    const val INT = "int"
    const val LCM = "lcm"
    const val LESS = "<"
    const val LESS_EQ = "<="
    const val MAX = "max"
    const val MIN = "min"
    const val MINUS = "-"
    const val MINUS_P = "minusp"
    const val NOT_EQ = "/="
    const val NULL = "null"
    const val ODD_P = "oddp"
    const val ONE_MINUS = "1-"
    const val ONE_PLUS = "1+"
    const val PLUS = "+"
    const val PLUS_P = "plusp"
    const val QUOTE = "'"
    const val TIMES = "*"
    const val ZERO_P = "zerop"
}